### ISSUE TITLE
[BUG] (Light theme) Hidden bullet on unordered list in preview

### ISSUE THREAD

**Issue by SirSpidey** [Braweria/Spectrum#10]
Thanks for address the external links in #9. 

After loading that update, I see another issue: the unordered list "bullet" is not visible in preview mode. 

Let me know if you're still working on the theme and don't need issues created.

**Screenshots**
![image](https://user-images.githubusercontent.com/8194208/110323058-0a797300-7fe2-11eb-8fcf-7d75e78ba8f1.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.2
 - Obsidian Version: 0.11.5

```md
---
aliases: [Testing lite theme]
created: "2021-03-08"
source: 
cssclass: [matrix]
tags: [ actions/-📥Inbox ]
---

# Testing spectrum light theme

## Lists

### Unordered list
- [ ] Checkbox
- List item

### Ordered list
1.  Item 1
2.  Item 2


## Links

[[2021-03-08|Gratitude journal 2021-03-08]]

[Spectrum Obsidian Theme](https://github.com/Braweria/Spectrum)

## Task review (Eisenhower matrix)

### Tasks

| Urgent | Not Urgent |
| --- | --- |
| ![[template-eisenhower#Urgent Important]] | ![[template-eisenhower#Not Urgent Important]] |
| ![[template-eisenhower#Urgent Not Important]] | ![[template-eisenhower#Not Urgent Not Important]] |

### Urgent/Important
Do it immediately

- [ ] 

### Not Urgent/Important
Decide when you'll do it

- [ ] 

### Urgent/Not Important
Delegate to someone

- [ ] 

### Not Urgent/Not Important
Do it later

- [ ] 
```

**Comment by Braweria** [comment]
> Let me know if you're still working on the theme and don't need issues created.

I appreciate issues because that way I can fix stuff I did not see previously. 👍 

I'll have a fix ready for tomorrow.

**Comment by Braweria** [comment]
3 days later than promised, but here it is. :)
