### ISSUE TITLE
[BUG] Additional space after comments

### ISSUE THREAD

**Issue by danieltomasz** [Braweria/Spectrum#11]
**Describe the bug**

Spectrum theme render additional space after line with comments
**To Reproduce**

Code here
```
## Today tasks
%%Put the stuff here%%
- 7PM Week review
```
produces in default Obsidian
![image](https://user-images.githubusercontent.com/7980381/110970686-469e3200-835a-11eb-9a42-bfe0504b2c40.png)

With spectrum theme
![image](https://user-images.githubusercontent.com/7980381/110970798-65042d80-835a-11eb-9132-1bfa2e47c229.png)

**Expected behavior**

Spectrum theme will not render comments as empty line
![image](https://user-images.githubusercontent.com/7980381/110971219-df34b200-835a-11eb-8dd7-c8f465c24ab0.png)

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] MacOS BigSur
 - Obsidian Version: [e.g. 22] 0.11.5

**Additional context**

**Comment by Braweria** [comment]
Oh wow, that is weird. 🤔 
I will take a look into it, thanks for letting me know.

**Comment by Braweria** [comment]
I looked into it, and I get the same break with default as well as with Spectrum. When using a comment, it creates an additional  element, which causes the empty line.

**Comment by DannyDies** [comment]
Hello👋 The same thing happens with line reference. 
![ref](https://user-images.githubusercontent.com/70198933/120287831-49108800-c2c8-11eb-9bf3-2c7edee3dd90.gif)

**Comment by Braweria** [comment]
@DannyDies Very curious, have you tested it with the vanilla theme as well?

**Comment by DannyDies** [comment]
In default and other themes works fine. Disable all snippets too. Seems like a flexbox problem(other themes I've tested haven't it)

**Comment by DannyDies** [comment]
In my case, I disabled `.markdown-preview-view.is-readable-line-width .markdown-preview-sizer`. Then all stuff align to the left, so I disabled all css from 2 section(Text area) and all just fine for my issue. Flex features not important for me right now. But if you solve it another way, please, let me know.

**Comment by Braweria** [comment]
Obsidian adds an empty `div` and `p` container when you have a reference.  
```html
<div>
  <p>a test note </p>
  <div></div>
  <p></p>
</div>
```
is what it outputs when you write  
```markdown
a test note ^reference
```
But if you do *not* have a reference, then obsidian outputs this instead, which is how it should be:  
```html
<div>
  <p>a test note </p>
</div>
```

**Comment by DannyDies** [comment]
@Braweria i tried to adjust that property. It makes effect. But I'm so tired to think tonight. Can it help?
```css
.markdown-preview-view div p{
  margin-bottom: 0rem;
}

**Comment by Braweria** [comment]
@DannyDies I have discussed that issue with people on the Discord Server and made a bug report on the Forum, with version 0.12.9 this will be fixed.

**Comment by DannyDies** [comment]
Oh, it nice. Thanks for your efforts! Waiting 12.9.
