### ISSUE TITLE
[BUG] Codeblock's language tag gets over content.

### ISSUE THREAD

**Issue by VitorPaludetto** [Braweria/Spectrum#14]
**Describe the bug**

When a language is specified on a codeblock a "tag" identifying the language appears on the right-bottom of the block, but when the last line of this codeblock is too long, the tag get's over the content of the line, as shown in the screenshot.

**To Reproduce**
1. Write any code inside a codeblock identifying the language, ex: 
 \```javascript
{code}
\```
2. If the line is too big the tag gets in the way of the content.

**Screenshots**
![issueSpectrumObsidian](https://user-images.githubusercontent.com/29387670/119601595-dbdc8e80-bdbf-11eb-9c66-5b022eb2750a.png)

**Desktop:**
 - OS: Ubuntu 20.04
 - Obsidian Version: 0.12.3 (flatpak)

**Comment by Braweria** [comment]
The language name in a code block had a few issues, for now, I have removed it entirely.
