### ISSUE TITLE
[BUG] Too much space between the headings and bullet lists

### ISSUE THREAD

**Issue by WilliamDev588** [Braweria/Spectrum#15]
**Screenshots**
<img width="154" alt="Screen Shot 2021-06-24 at 19 35 55" src="https://user-images.githubusercontent.com/83950576/123263637-67fae680-d523-11eb-9275-f7e595674742.png">

**Desktop (please complete the following information):**
 - OS: macos 11.4
 - Obsidian Version: 0.12.5

**Comment by Braweria** [comment]
In both Spectrum and the default theme, they have a margin of about 14-15 pixel on headings and on lists.  

I can provide you with a custom snippet, just tell me where you want to have the margin be lowered. Heading? Then everything will be closer to heading. List? Then everything will be closer to lists.

@WilliamDev588

**Comment by Braweria** [comment]
Due to a lack of response, I will be closing the issue for now.
