### ISSUE TITLE
[BUG] Nested ordered lists don't have colored tab lines

### ISSUE THREAD

**Issue by aviskase** [Braweria/Spectrum#16]
**To Reproduce**
Use nested ordered lists or combo of ordered and unordered lists.

```
test1

- item1
- item2
	- item3
	- item4
		- item5
		- item6

test2

1. item1
2. item2
	1. item3
	2. item4
		1. item5
		2. item6

test3 

1. item1
2. item2
	1. item3
	2. item4
		- item5
		- item6
```

**Expected behavior**
I expected "tab lines" (or whatever it is called) to be used for ordered and unordered lists the same way (always have a bright yellow line), especially in the case of mixing both types.

**Screenshots**
![image](https://user-images.githubusercontent.com/3819473/123585759-b7eedd00-d7b1-11eb-963e-f755638975ad.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu (Linux)
 - Obsidian Version: v0.12.7

**Comment by aviskase** [comment]
BTW, I've just noticed, looks like ordered lists' items also have different vertical spacing compared to unordered.

**Comment by Braweria** [comment]
I noticed you are using snippets to change some appearance. I have pushed a new update for the lists 564c0827c5e10813075a28d391ccdf642b8a7915, could you please check if it now works for you? On the default Spectrum theme and then against your custom snippets.

**Comment by aviskase** [comment]
> I noticed you are using snippets to change some appearance. I have pushed a new update for the lists [564c082](https://github.com/Braweria/Spectrum/commit/564c0827c5e10813075a28d391ccdf642b8a7915), could you please check if it now works for you? On the default Spectrum theme and then against your custom snippets.

Yeah, but those are just for font-family and colors, so they shouldn't affect it.


<img src="https://user-images.githubusercontent.com/3819473/123683734-91b15780-d81a-11eb-90b6-9577902e6961.png" width="200" >

Looks good, except mixed version. Just need to add these selectors to make it work too:

```
ul ol,
ol ul,
```

**Comment by Braweria** [comment]
you are absolutely right, it has been added: 0c2d57a3c961c6e010b13bb0d1bb8b23052bae86

**Comment by aviskase** [comment]
Huh, scss file is good, but the built version doesn't have `::before` blocks changes for some reason o_O

**Comment by Braweria** [comment]
> Huh, scss file is good, but the built version doesn't have `::before` blocks changes for some reason o_O

Should be fixed now.
