### ISSUE TITLE
Need help in tweaking the css to decrease the gap between Heading and Content?

### ISSUE THREAD

**Issue by iamsubh** [Braweria/Spectrum#17]
I feel the gap between headings and contents under them is little bit on the higher side. Same with the gap between paragraphs too.

I tried to find the properties like padding or margin of the header, paragraph tags but failed. 

Can you please guide me where to find them and tweak them in the css or give me a snippet of code?

![with readable line length turned on](https://user-images.githubusercontent.com/80085964/128143597-87966a79-e529-4446-9498-3a75c39dc5e7.jpg)

![gap between paragraphs](https://user-images.githubusercontent.com/80085964/128145743-7b690bf8-97e6-4fa9-aa0c-f4d3db15ebd9.jpg)

**Comment by iamsubh** [comment]
I figured out the code where paragraph gap can be tweaked. 

![figured out para gap code](https://user-images.githubusercontent.com/80085964/128195032-3e634eb7-4603-4ec5-9742-8b514d53fb95.jpg)

But still unable to find out the Heading and bullet point spacing.

**Comment by Braweria** [comment]
@iamsubh 
The headings use the standard margin that Obsidian provides. And lists also use the default margin of the user agent.  
![image](https://user-images.githubusercontent.com/62669899/128210949-213a47d2-4d58-435a-a0a1-1dacf851b1cb.png)

If you want to change them with a snippet, just target `h1` to `h6`  and `ul` to change the margin.

**Comment by iamsubh** [comment]
> If you want to change them with a snippet, just target `h1` to `h6` and `ul` to change the margin.

Thank you very much mate. I was finally able to tweak all those stuff I wanted to.

### Here are the things that I modified.

![the final tweaked code for spacing and gaps](https://user-images.githubusercontent.com/80085964/128567672-0f8718bb-666c-4004-8349-156e56cbffcc.jpg)

### Here is the final result that I completely love now. 

![Result after the final tweaking](https://user-images.githubusercontent.com/80085964/128567700-b62400b3-bc1b-419e-8217-9182542364f6.jpg)

**Comment by Braweria** [comment]
awesome, glad it got fixed. :)
