### ISSUE TITLE
[BUG] Bullet missing after export to PDF 

### ISSUE THREAD

**Issue by aaronooi007** [Braweria/Spectrum#23]
**Describe the bug**
Outliner bullet missing after export to PDF. This resulted the bullet items difficult to differentiate. 

**To Reproduce**
1. Open a note that contain multi-level bullet
2. Goto "More Options" --> Export to PDF
3. Click 'Export to PDF'
4. Open the PDF viewer. 

**Expected behavior**
Each bullets should be printed out in the exported PDF 

**Screenshots**
![image](https://user-images.githubusercontent.com/31320116/133070084-112d6ef1-79fa-4daf-aa33-dc607f925b60.png)

**Desktop (please complete the following information):**
 - OS: Windows 10 
 - Obsidian Version: v0.22.15

**Comment by Braweria** [comment]
That's a really weird issue, I will investigate.

**Comment by Braweria** [comment]
Not sure what cuases it, but Spectrum 1.0.0 got a fix for that, it would look like this:
![image](https://user-images.githubusercontent.com/62669899/133103067-abe923b6-91b3-4232-8f5d-8d7fc57da28d.png)

**Comment by Braweria** [comment]
@aaronooi007 with the new version out, this shouldn't be an issue anymore.
