### ISSUE TITLE
[BUG] Theme does not work with Breadcrumbs plugin grids

### ISSUE THREAD

**Issue by mkasu** [Braweria/Spectrum#24]
**Describe the bug**
This theme does not seem to work well with the [Breadcrumbs](https://github.com/SkepticMystic/breadcrumbs) plugin, which is used to create navigational breadcrumbs on top of the preview view.

In other themes, its grid view can display multiple "paths" from the current note to the index note through this grid-like visualization. But in Spectrum it will just stack all elements vertically, without being able to see each paths.

**To Reproduce**
1. Use breadcrumbs plugin
2. Activate "grid" view
3. Have some hierarchy with multiple paths

**Expected behavior**
It should look like in other themes, indicating path of all breadcrumbs, instead of just stacking all boxes.

**Screenshots**
Example 1:

![ex1_obsidian](https://user-images.githubusercontent.com/798036/135569077-0a5eb9ee-9cda-4f1d-8a47-93fa7fda7838.png)
![ex1_spectrum](https://user-images.githubusercontent.com/798036/135569078-1d3635fc-890b-4a9a-9393-e1d5f74d3b8c.png)

Example 2

![ex2_obsidian](https://user-images.githubusercontent.com/798036/135569074-d7848c4f-15e9-470e-9944-a46874bd6381.png)
![ex2_spectrum](https://user-images.githubusercontent.com/798036/135569133-9a3c3ba5-aabb-4d3a-aa45-64fa57ff7eb7.png)

**Desktop (please complete the following information):**
 - OS: macOS
 - Obsidian Version: 0.12.16

**Comment by Braweria** [comment]
I will be looking into this, thanks for the issue, sorry for the delay.

**Comment by Braweria** [comment]
fixed in e3c72f3
