### ISSUE TITLE
[FEAT] Styles made permanent without adding frontmatter to every note

### ISSUE THREAD

**Issue by cjl12377** [Braweria/Spectrum#26]
**Is your feature request related to a problem? Please describe.**
I like many of your features and I'd like to make them a permanent CSS snippet so I don't have to add frontmatter to every note. Is this feature somewhere in the pipeline?

**Comment by Braweria** [comment]
@cjl12377 Yes! I plan on releasing an additional folder called "snippets" that will contain the features as snippets that you can just add to your snippets folder on Obsidian.

**Comment by Braweria** [comment]
i have now updated the repo with a snippets folder, you can check it out, it's in the root's directory.
