### ISSUE TITLE
[BUG] Something wrong with the Latex in preview mode

### ISSUE THREAD

**Issue by Yaozhuwa** [Braweria/Spectrum#27]
**Describe the bug**
The picture below shows the problem.
![image](https://user-images.githubusercontent.com/28787183/142251727-6e48b0f7-52b2-4c60-886a-1268f7f130ff.png)

**To Reproduce**
```txt
$\gamma=0.8$

> $x$ 的 1 范数: $\|x\|_{1}=\left|x_{1}\right|+\left|x_{2}\right|+\cdots+\left|x_{n}\right|$
```

**Expected behavior**
Picture below is the preview under default theme.
![image](https://user-images.githubusercontent.com/28787183/142252144-14f09d73-acca-47f5-83b3-2441d9b4c0e6.png)

**Desktop (please complete the following information):**
 - OS: Windows, Ubuntu18.04
 - Obsidian Version: 0.13.2

**Comment by YangLeiSX** [comment]
When I use `\hat` in LaTeX, it is also not correct, like this.
<img width="415" alt="截屏2021-11-23 12 51 48" src="https://user-images.githubusercontent.com/35104346/142972901-6dc36f11-947f-4708-b3ab-f9d729819dca.png">

Expected like this.
<img width="350" alt="截屏2021-11-23 12 53 18" src="https://user-images.githubusercontent.com/35104346/142973024-3f386423-76a5-438b-9381-fde09486f8aa.png">

**Comment by Braweria** [comment]
That's weird, I will have to take a look, it might be the font. If the font doesn't support it, I will have to use another font for math specifically.

**Comment by Braweria** [comment]
I found the issue:
![image](https://user-images.githubusercontent.com/62669899/142984705-35e363cb-b2a3-4bce-9fb8-60827f4d1aa0.png)
I will make a fix for it later today.

**Comment by Braweria** [comment]
https://github.com/Braweria/Spectrum/commit/ff3cf3582d2b1fb0584302c7ba7f99b428982f18
Issue got fixed, it should now work as expected.

**Comment by YangLeiSX** [comment]
Thaaaaaanks，I love this theme!

**Comment by Braweria** [comment]
> Thaaaaaanks，I love this theme!

I'm glad you love it!
