### ISSUE TITLE
Atleast one screenshot please

### ISSUE THREAD

**Issue by viaahmed** [Braweria/Spectrum#28]

**Comment by Braweria** [comment]
Please describe the issue you are having. @viaahmed

**Comment by viaahmed** [comment]
Sorry for not clarifying. I was requesting if this a theme, would you please add a screenshot of how it looks. Thanks

**Comment by Braweria** [comment]
I will provide more screenshots, in the meantime there is a single PNG in the root of the repo. It is required to upload themes to Obsidian.  

https://github.com/Braweria/Spectrum/blob/main/SpectrumPreview.png

This is an older version from when i first published it, a better screenshot is in the making.

**Comment by viaahmed** [comment]
🐺 🤭

**Comment by Braweria** [comment]
Can you tell me what kind of images you would like to be shown? @viaahmed

**Comment by Braweria** [comment]
For now a new image is now shown in the readme, you can also find it here:  
https://github.com/Braweria/Spectrum/blob/main/SpectrumPreview.png
