### ISSUE TITLE
[BUG] Title bar and pop-over status message show black on black (invisible text)

### ISSUE THREAD

**Issue by aquatix** [Braweria/Spectrum#30]
**Describe the bug**
The title bar of the Obsidian application does not have visible text, and the toast pop-over with status message that is shown when something is updated has the same issue (looks like a black bar).

**To Reproduce**
1. Open Obsidian.
2. Look at the title bar.
3. See nothing.
4. Same when on an Android device and the vault for example finishes scanning (also see screenshot).

**Expected behavior**
Visible text :)

**Screenshots**
See comment.

**Desktop (please complete the following information):**
 - OS: Linux desktop, Android phone.
 - Obsidian Version: 0.12.19

**Comment by aquatix** [comment]
![Screenshot_20211206-121455.png](https://user-images.githubusercontent.com/629545/144846714-62844701-50bc-480e-b33b-a54a695a4fb7.png)

**Comment by aquatix** [comment]
Thanks for this great-looking theme!

**Comment by aquatix** [comment]
Oh, I just realised the titlebar does not show any text at all, because of the 'display: none' on `.titlebar-text`: https://github.com/Braweria/Spectrum/blob/main/obsidian.css#L761

Any reason you are doing this, apart from it looking more clean? I kinda like the clean look without the text, but I have multiple vaults, so having a title is helpful.

Not sure if this is related to that pop-over status message though, might still be an issue.

**Comment by Braweria** [comment]
@aquatix 
They are not related to each other. I hid the titlebar, so that plugins that use that space can work with that space better, example:  
![image](https://user-images.githubusercontent.com/62669899/146668490-de3fb89e-5eb3-4830-b2c4-6fe98c4f6f0e.png)

I can release a snippet, though, where you can choose it yourself. I believe that would be a good workaround. What do you think?

**Comment by aquatix** [comment]
I was not aware of plugins using the titlebar, that sounds useful indeed. A snippet would certainly help me, making better use of the Obsidian GUI sounds good :)

Thanks in advance for fixing the Snackbox!

**Comment by Braweria** [comment]
Snippet now exists in the Snippet folder.

**Comment by aquatix** [comment]
Nice, I saw the snippet, thanks!

How exactly would that work? Do I need to manually add the content of the snippet to the final .css file, or is it preferred to compile the project using the snippet somehow? Just thinking about how to use it :)

**Comment by aquatix** [comment]
Also, which plugins do you use that make use of that space? Sounds useful.

**Comment by Braweria** [comment]
You save the snippet css in the snippet folder of Obsidian.  You can open the right folder from the appearance tab.  
![image](https://user-images.githubusercontent.com/62669899/148898546-965939df-79ba-49d9-9384-3132a33c9fa0.png)

The Plugin is also the Quick Explorer, you can see the GitHub here: https://github.com/pjeby/quick-explorer

**Comment by aquatix** [comment]
Oh, I totally overlooked that "CSS snippets" config option, thanks.

Quick Explorer looks useful, but I don't have nested directories in my vaults, so I don't think I'll use it. Maybe I can use the title bar for something else though :)

Anyways, thanks for the changes and fixes, I love this theme!
