### ISSUE TITLE
[BUG] "max-width: fit-content" produces full-width lines when displaying tasks with the "Obsidian Tasks" plugin

### ISSUE THREAD

**Issue by phil-holland** [Braweria/Spectrum#33]
**Describe the bug**
In reading mode, when rendering a task list with [Obsidian Tasks](https://github.com/schemar/obsidian-tasks), the corresponding `div` is stretched to the full width of the page. In live-preview editing mode, the width is correct.

After investigating the theme CSS file, it seems that removing the `max-width: fit-content;` line (originating in [this scss file](https://github.com/Braweria/Spectrum/blob/4369d1e615d019cecd5bc049295d44738d080a23/SCSS/_blocks/_textarea/_preview.scss), I'm assuming?) fixes the issue (but I'm not sure if removing this would break something else).

I've also noticed that removing the `min-width: 750px` entry in the same CSS block stops rendered task blocks from stretching outside the width of the screen on small displays (i.e. on mobile). And also apparently fixes the same behaviour in metadata blocks - i.e. https://github.com/Braweria/Spectrum/issues/29

**To Reproduce**
1. Install the Obsidian Tasks plugin
2. Create a new note with the contents:

~~~
### Task List

```tasks
not done
due after 2022-01-02
due before 2022-01-04
```

### Other Text

Consequat semper viverra nam libero justo laoreet. Sapien nec sagittis aliquam malesuada bibendum arcu vitae elementum curabitur. Venenatis lectus magna fringilla urna porttitor rhoncus. Tristique et egestas quis ipsum suspendisse ultrices gravida. Risus quis varius quam quisque id diam vel quam. Quis viverra nibh cras pulvinar mattis nunc. Aliquam vestibulum morbi blandit cursus risus at ultrices mi tempus. Quis hendrerit dolor magna eget est.

---

### Task Creation

- [ ] #task Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Tempor nec feugiat nisl pretium fusce id. 📅 2022-01-03

---
~~~

3. Switch to reading mode

**Expected behavior**
The `div` should be limited to the same maximum width as all other elements in the note.

**Screenshots**

In *live-preview editing* mode:

![image](https://user-images.githubusercontent.com/6163077/147874834-51718bcc-0d69-487c-95c9-aa2e0ac74cd6.png)

In *reading* mode:

![image](https://user-images.githubusercontent.com/6163077/147874839-1953d1cb-a8a2-46b6-be2c-3a3793ee9c42.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Obsidian Version: v0.13.14

Thank you for all the work on the theme - I'm a big fan!

**Comment by Braweria** [comment]
I hope this will fix the issue you were having, and I'm glad you like the theme!

**Comment by phil-holland** [comment]
Yep, all looks good now, thanks!
