### ISSUE TITLE
[BUG] [LP] List Styles not working

### ISSUE THREAD

**Issue by SuperNoobTao** [Braweria/Spectrum#35]
**Describe the bug**
hello,I am a newer of obsidian,and I like your theme and 'List Style', but I am confused about the following questions:
Does the 'List Styles' only work  in the reading view? I switch to the '**Live Preview**' mode's editing view, it does not work.

**To Reproduce**
To create a deeply structured list .

**Expected behavior**
In 'live preview' mode's editing view, the 'List Styles'  can work .

**Screenshots**
![image](https://user-images.githubusercontent.com/16486344/148810158-c2727325-75be-4735-bc49-e2ecc6a8e318.png)

**Desktop (please complete the following information):**
 - OS: [MAC 15.7]
 - Obsidian Version: [0.13.19]

**Additional context**
My English is not good,if what I said is not very clear, please leave a message.
I would appreciate if you can spend time to help me.
Thanks you very much.~

**Comment by Braweria** [comment]
Yes, with the introduction of Live Preview I was not able to fix some of the issues that came with it yet. Some other things, like URLs or CHeckboxes, don't work in Live Preview yet, either.  

It is something I want to get around to when I have the time for it and fix all the LP issues.

**Comment by SuperNoobTao** [comment]
Thank you very much for your response, I will keep watching~

**Comment by Braweria** [comment]
So I made some fixes a while back, and lists in Live Preview do not work the same as lists in Preview Mode. In PM they're properly marked with UL and LI, but in LP they're all only DIVs under each other, no nesting. So special styling cannot be applied to them.
