### ISSUE TITLE
How do I tweak the code to change the spacing/gap between heading, content and such?

### ISSUE THREAD

**Issue by IPushedU** [Braweria/Spectrum#36]
The title describes the issue i wanted to list.
I did a search before writing this, so this issue is based on issue #17. But as I'm noting familiar with css, I thought of just asking it here. Thanks.
Absolutely love the theme b.t.w, it also uses my favorite color yellow.

**Comment by Braweria** [comment]
You can try to copy what the person wrote
https://github.com/Braweria/Spectrum/issues/17#issuecomment-894504467
save it as a snippet `MyTweaks.css` in the snippet folder of Obsidian.
