### ISSUE TITLE
Preview mode align issue

### ISSUE THREAD

**Issue by tmllull** [Braweria/Spectrum#38]
Since last (or 2 last) update, the preview mode not works as expected, only blocks with large width expand into the page; the others keeps on center, not at the left (into the limits to show in center of the page).

Spectrum theme
![imagen](https://user-images.githubusercontent.com/5560652/157191513-af8bf5bc-b88c-40a5-94c6-40e6ee4d80dd.png)

Default theme
![imagen](https://user-images.githubusercontent.com/5560652/157191563-b50c25dc-1d60-46b5-83a3-4939d26bb468.png)

**Comment by tmllull** [comment]
Hi again. I update again the theme and now seems that this issue not occurs. I close it.

Sorry for this inconvenience.

Regards.

**Comment by Braweria** [comment]
Yeah, I noticed this issue so I made a fix for it. 
Thanks for letting me know, though!
