### ISSUE TITLE
[BUG] Icons provided by Icon Shortcodes appear off the bottom of the line

### ISSUE THREAD

**Issue by jmccance** [Braweria/Spectrum#39]
**Describe the bug**

When using [aidenx/obsidian-icon-shortcodes.](https://github.com/aidenlx/obsidian-icon-shortcodes), non-emoji icons are aligned with the top of the icon on the bottom of the line. (See screenshots.

**To Reproduce**

1. Install "Icon Shortcodes" community plugin
2. Enable Spectrum theme
3. Type `Some text :luc-github` and hit enter to select the icon.
4. Observe alignment issues

**Expected behavior**

The icon be aligned with other text on the line.

**Screenshots**

Given this text:

```
Text aligns properly
🍋🍎🍊 Align more-or-less properly, but overlap
:luc_github::fas_folder:Icons provided by icon-shortcodes are misaligned and also overlap
```

Spectrum renders like this:

![image](https://user-images.githubusercontent.com/764591/157706752-cfcdd77f-ded7-4634-933f-6b6bb5bb039d.png)

While the default theme renders like this:

![image](https://user-images.githubusercontent.com/764591/157706794-dbf509a8-3b5c-45d5-9bd8-d69a3346d278.png)

**Desktop (please complete the following information):**
 - OS: macOS 12.2.1
 - Obsidian Version: v0.13.31

**Additional context**

I recognize this might not specifically be an issue with Spectrum, and might actually be a bug with the Icon Shortcodes plugin or just a weird interaction between Spectrum and the plugin. I decided to start with an issue here, since it seems to not occur when using the default theme.

**Comment by Braweria** [comment]
I will have to investigate the styling of the icons to make a fix. I will take a look.

**Comment by Braweria** [comment]
Should be fixed now.

**Comment by jmccance** [comment]
Thank you! 🎉 Confirmed it's working as expected for me now.
