### ISSUE TITLE
Ghost "frontmatter language-yaml" appearing in Preview mode [BUG]

### ISSUE THREAD

**Issue by I-Pch** [Braweria/Spectrum#4]
**Describe the bug**
When using YAML metadata (at least to create `Alias`) in Edit Mode, there's a `frontmatter language-yaml` appearing in the note in `Preview Mode`

**To Reproduce**
1. Go to `Obsidian` using `Spectrum` as theme.
2. Create a note. 
3. Add `Alias` or `Aliases` for this note
3. Open this note in `Preview Mode`
4. See `frontmatter language-yaml` appearing somewhere on the note (the emplacement may be different than my screenshot)

**Expected behavior**
`frontmatter language-yaml` shouldn't be there 😊 .

**Screenshots**
<img width="1101" alt="YAML" src="https://user-images.githubusercontent.com/77828085/109148648-d216a100-7766-11eb-9c16-3c7476c0779e.png">
<img width="1101" alt="Without Alias" src="https://user-images.githubusercontent.com/77828085/109148702-e490da80-7766-11eb-8a9d-47e0e5cbdcc5.png">

**Desktop**
 - OS: MacOS Big Sur (version 11.2.1)
 - Obsidian Version: 0.11.0 (installer v0.10.1)

**Additional Info**
Concerning the emplacement of the `frontmatter language-yaml`: it seems to be "stuck" at the bottom right of the screen on short notes  and when scrolling on a longer note, it stays at that very specific emplacement.

![YAML](https://user-images.githubusercontent.com/77828085/109151522-92ea4f00-776a-11eb-944d-a1af63ab3357.gif)

**Comment by ruthvikvegunta** [comment]
I have the same for language bash as well, fun fact is it only appears in few notes, not in all the notes where I have a bash snippet

**Comment by Braweria** [comment]
Really weird. I don't have a Mac, so my testing capabilities are limited. Could another Mac user please paste this into their note and send me a screenshot of what it looks like?

> \`\`\`js
> const greetings = name => {
>   return `Hello §{name}, how are you?`
> }
> 
> console.log(greetings(Steph));
> // Hello Steph, how are you?
> \`\`\`

It should look like this:

![image](https://user-images.githubusercontent.com/62669899/109188859-a78f0d00-7793-11eb-8531-5eea55ae214e.png)

**Comment by I-Pch** [comment]
Here you go @Braweria 😊 

<img width="1101" alt="Testing" src="https://user-images.githubusercontent.com/77828085/109193617-db206600-7798-11eb-9578-f87515fd45ab.png">

From what you're asking, it seems like the ghostly 'frontmatter language-yaml' is there because it's interpreted as a code language, I guess 😊 . Seems like both are now superimposed in preview mode

I don't have the copy-button for code block plugin though, if that helps 🤷‍♀️ .

**Comment by Braweria** [comment]
It looks like it isn't relating the position to its parent, but rather to the note itself. It might be something that Mac does differently, I will have to take a closer look to see if I can fix that somehow.

**Comment by I-Pch** [comment]
My CSS capabilities are very limited (the last time I fully customized a CSS was at least 20 years ago 😇 ) but I'm slowly relearning things 😉 . If you need more testing, don't hesitate to ping me though 😉.

And you might be completely right, it might be because I'm on a Mac.

Thank you for trying and looking into this 😁 !

**Comment by I-Pch** [comment]
Seems like the fix did the trick 🥳 !!!

Thank you very much @Braweria 👍 😁 !

<img width="897" alt="Perfect!" src="https://user-images.githubusercontent.com/77828085/109205908-87694900-77a7-11eb-9025-426ec99811fe.png">
