### ISSUE TITLE
[FEAT] style-settings for list and table

### ISSUE THREAD

**Issue by akhil-free** [Braweria/Spectrum#46]
**Describe the solution you'd like**
kindly make list style, table style change-able  from style settings .

**Comment by Braweria** [comment]
can you tell me what you would like to be able to change?

**Comment by akhil-free** [comment]
switch between list styles ie. 
![1](https://user-images.githubusercontent.com/99335642/158731630-6638a887-8fbb-46a6-84a1-174c9bb98f5b.png)
and
![2](https://user-images.githubusercontent.com/99335642/158731637-f46efb81-3ac0-4206-9ae3-ba18966a2f57.png)

similarly for tables
