### ISSUE TITLE
[FEAT]Automatically create new row if the current row run out of space

### ISSUE THREAD

**Issue by trungng2006** [Braweria/Spectrum#5]
**Is your feature request related to a problem? Please describe.**
If i put more boards in, then they are squeezed into 1 line.
![image](https://user-images.githubusercontent.com/71961905/109417017-bc220e00-79fc-11eb-84b9-a12078e4ebca.png)

**Describe the solution you'd like**
Would it be possible to make it automatically go down new line/row if run out of space?
![image](https://user-images.githubusercontent.com/71961905/109417027-c80dd000-79fc-11eb-82ef-3ac7181ab538.png)

**Additional context**

**Comment by Braweria** [comment]
The Kanban Board wraps now when there are too many. 
--> 1d7c75c59991a75b42d1184cf9205b0a5f1b9db8

![image](https://user-images.githubusercontent.com/62669899/109973543-d14ab580-7cf8-11eb-8520-eb13c42aa01a.png)
