### ISSUE TITLE
Reason of stopped maintenance

### ISSUE THREAD

**Issue by aquatix** [Braweria/Spectrum#50]
Hey :)

I have been using your theme since forever, and really loving it (the colours for example just really work for me, and the same goes for the font), so I was a bit sad to see you stopped maintaining it.

What's the reason you stopped? Is it a lot of work, or did you stop using Obsidian or the theme itself?

Just wondering :)

Kind regards and thanks for the work!

**Comment by Braweria** [comment]
I have lost interest in maintain the theme for obsidian, with the many changes that come and introduce breaking changes. There is also no proper documentation for styling, which makes it even harder.  

Regardless of those, I actually did start moving away from Obsidian, but that has nothing to do with me stopping maintaining it. I still have the repo up and not archive, so people are more than welcome to send PRs, and I will check them out when possible, or other people can review them.

**Comment by Braweria** [comment]
@aquatix 
I am currently using Dendron, which is an extension for VS Code. YOu can import an obsidian vault into it as well and it will convert it to the Dendron Hierarchy.  
It supports backlinking, but it is not required to create a graph. The Graph is created by hierarchy, and the backlinks are additional arrows on that graph.  
https://wiki.dendron.so/
You can check it out here
