### ISSUE TITLE
Light theme URLs too little contrast

### ISSUE THREAD

**Issue by SirSpidey** [Braweria/Spectrum#9]
**Describe the bug**
Thanks for providing a light theme. 
Unfortunately, I think that the external URLs in edit mode are too translucent with too little contrast to be visible. 

**Screenshots**
![image](https://user-images.githubusercontent.com/8194208/110155228-54304680-7db3-11eb-9e28-74e7b75b922a.png)

**Desktop (please complete the following information):**
 - OS: MacOS 11.2
 - Obsidian Version: 0.11.5

**Comment by Braweria** [comment]
I'll make a fix for it at the weekend. Thanks for telling me.

**Comment by Braweria** [comment]
Has been fixed. da5254a914eda6d1fb4e16395c446b431c59229e
